// Portions derived from HAP-NodeJS (https://github.com/homebridge/HAP-NodeJS), Apache License 2.0. Modified for CameraBridge.
// GENERATED by Tools/hap-definitions/generate.mjs from HAP-NodeJS lib/CharacteristicDefinitions.ts (research brief §3.4 subset).
// Do not edit by hand: change the generator's subset and rerun it.

import Foundation

extension CharacteristicType {
    // MARK: Identity

    public static let identify = CharacteristicType(
        uuid: "14", name: "Identify", format: .bool, permissions: [.pairedWrite])
    public static let manufacturer = CharacteristicType(
        uuid: "20", name: "Manufacturer", format: .string, permissions: [.pairedRead], maxLength: 64)
    public static let model = CharacteristicType(
        uuid: "21", name: "Model", format: .string, permissions: [.pairedRead], maxLength: 64)
    public static let name = CharacteristicType(
        uuid: "23", name: "Name", format: .string, permissions: [.pairedRead], maxLength: 64)
    public static let serialNumber = CharacteristicType(
        uuid: "30", name: "Serial Number", format: .string, permissions: [.pairedRead], maxLength: 64)
    public static let firmwareRevision = CharacteristicType(
        uuid: "52", name: "Firmware Revision", format: .string, permissions: [.pairedRead])
    public static let hardwareRevision = CharacteristicType(
        uuid: "53", name: "Hardware Revision", format: .string, permissions: [.pairedRead])
    public static let configuredName = CharacteristicType(
        uuid: "E3", name: "Configured Name", format: .string, permissions: [.pairedRead, .pairedWrite, .events])
    public static let version = CharacteristicType(
        uuid: "37", name: "Version", format: .string, permissions: [.pairedRead], maxLength: 64)

    // MARK: RTP stream management

    public static let supportedVideoStreamConfiguration = CharacteristicType(
        uuid: "114", name: "Supported Video Stream Configuration", format: .tlv8, permissions: [.pairedRead])
    public static let supportedAudioStreamConfiguration = CharacteristicType(
        uuid: "115", name: "Supported Audio Stream Configuration", format: .tlv8, permissions: [.pairedRead])
    public static let supportedRTPConfiguration = CharacteristicType(
        uuid: "116", name: "Supported RTP Configuration", format: .tlv8, permissions: [.pairedRead])
    public static let selectedRTPStreamConfiguration = CharacteristicType(
        uuid: "117", name: "Selected RTP Stream Configuration", format: .tlv8, permissions: [.pairedRead, .pairedWrite])
    public static let setupEndpoints = CharacteristicType(
        uuid: "118", name: "Setup Endpoints", format: .tlv8, permissions: [.pairedRead, .pairedWrite])
    public static let streamingStatus = CharacteristicType(
        uuid: "120", name: "Streaming Status", format: .tlv8, permissions: [.pairedRead, .events])
    public static let active = CharacteristicType(
        uuid: "B0", name: "Active", format: .uint8, permissions: [.pairedRead, .pairedWrite, .events], minValue: 0, maxValue: 1, minStep: 1, validValues: [0, 1])

    // MARK: Recording management

    public static let supportedCameraRecordingConfiguration = CharacteristicType(
        uuid: "205", name: "Supported Camera Recording Configuration", format: .tlv8, permissions: [.pairedRead, .events])
    public static let supportedVideoRecordingConfiguration = CharacteristicType(
        uuid: "206", name: "Supported Video Recording Configuration", format: .tlv8, permissions: [.pairedRead, .events])
    public static let supportedAudioRecordingConfiguration = CharacteristicType(
        uuid: "207", name: "Supported Audio Recording Configuration", format: .tlv8, permissions: [.pairedRead, .events])
    public static let selectedCameraRecordingConfiguration = CharacteristicType(
        uuid: "209", name: "Selected Camera Recording Configuration", format: .tlv8, permissions: [.pairedRead, .pairedWrite, .events])
    public static let recordingAudioActive = CharacteristicType(
        uuid: "226", name: "Recording Audio Active", format: .uint8, permissions: [.pairedRead, .pairedWrite, .events, .timedWrite], validValues: [0, 1])

    // MARK: Operating mode

    public static let eventSnapshotsActive = CharacteristicType(
        uuid: "223", name: "Event Snapshots Active", format: .uint8, permissions: [.pairedRead, .pairedWrite, .events], minValue: 0, maxValue: 1, validValues: [0, 1])
    public static let homeKitCameraActive = CharacteristicType(
        uuid: "21B", name: "HomeKit Camera Active", format: .uint8, permissions: [.pairedRead, .pairedWrite, .events], minValue: 0, maxValue: 1, validValues: [0, 1])
    public static let cameraOperatingModeIndicator = CharacteristicType(
        uuid: "21D", name: "Camera Operating Mode Indicator", format: .bool, permissions: [.pairedRead, .pairedWrite, .events, .timedWrite], validValues: [0, 1])
    public static let manuallyDisabled = CharacteristicType(
        uuid: "227", name: "Manually Disabled", format: .bool, permissions: [.pairedRead, .events], validValues: [0, 1])
    public static let nightVision = CharacteristicType(
        uuid: "11B", name: "Night Vision", format: .bool, permissions: [.pairedRead, .pairedWrite, .events, .timedWrite])
    public static let periodicSnapshotsActive = CharacteristicType(
        uuid: "225", name: "Periodic Snapshots Active", format: .uint8, permissions: [.pairedRead, .pairedWrite, .events], validValues: [0, 1])
    public static let thirdPartyCameraActive = CharacteristicType(
        uuid: "21C", name: "Third Party Camera Active", format: .uint8, permissions: [.pairedRead, .events], validValues: [0, 1])
    public static let diagonalFieldOfView = CharacteristicType(
        uuid: "224", name: "Diagonal Field Of View", format: .float, permissions: [.pairedRead, .events], unit: .arcdegrees, minValue: 0, maxValue: 360)
    public static let videoAnalysisActive = CharacteristicType(
        uuid: "229", name: "Video Analysis Active", format: .uint8, permissions: [.pairedRead, .pairedWrite, .events])

    // MARK: Data stream

    public static let supportedDataStreamTransportConfiguration = CharacteristicType(
        uuid: "130", name: "Supported Data Stream Transport Configuration", format: .tlv8, permissions: [.pairedRead])
    public static let setupDataStreamTransport = CharacteristicType(
        uuid: "131", name: "Setup Data Stream Transport", format: .tlv8, permissions: [.pairedRead, .pairedWrite, .writeResponse])

    // MARK: Audio

    public static let mute = CharacteristicType(
        uuid: "11A", name: "Mute", format: .bool, permissions: [.pairedRead, .pairedWrite, .events])
    public static let volume = CharacteristicType(
        uuid: "119", name: "Volume", format: .uint8, permissions: [.pairedRead, .pairedWrite, .events], unit: .percentage, minValue: 0, maxValue: 100, minStep: 1)

    // MARK: Doorbell / switch

    public static let programmableSwitchEvent = CharacteristicType(
        uuid: "73", name: "Programmable Switch Event", format: .uint8, permissions: [.pairedRead, .events], minValue: 0, maxValue: 2, minStep: 1, validValues: [0, 1, 2])

    // MARK: Sensors

    public static let motionDetected = CharacteristicType(
        uuid: "22", name: "Motion Detected", format: .bool, permissions: [.pairedRead, .events])
    public static let occupancyDetected = CharacteristicType(
        uuid: "71", name: "Occupancy Detected", format: .uint8, permissions: [.pairedRead, .events], minValue: 0, maxValue: 1, minStep: 1, validValues: [0, 1])
    public static let currentAmbientLightLevel = CharacteristicType(
        uuid: "6B", name: "Current Ambient Light Level", format: .float, permissions: [.pairedRead, .events], unit: .lux, minValue: 0.0001, maxValue: 100_000)
    public static let currentTemperature = CharacteristicType(
        uuid: "11", name: "Current Temperature", format: .float, permissions: [.pairedRead, .events], unit: .celsius, minValue: -270, maxValue: 100, minStep: 0.1)
    public static let currentRelativeHumidity = CharacteristicType(
        uuid: "10", name: "Current Relative Humidity", format: .float, permissions: [.pairedRead, .events], unit: .percentage, minValue: 0, maxValue: 100, minStep: 1)
    public static let contactSensorState = CharacteristicType(
        uuid: "6A", name: "Contact Sensor State", format: .uint8, permissions: [.pairedRead, .events], minValue: 0, maxValue: 1, minStep: 1, validValues: [0, 1])
    public static let on = CharacteristicType(
        uuid: "25", name: "On", format: .bool, permissions: [.pairedRead, .pairedWrite, .events])

    // MARK: Status / battery

    public static let statusActive = CharacteristicType(
        uuid: "75", name: "Status Active", format: .bool, permissions: [.pairedRead, .events])
    public static let statusFault = CharacteristicType(
        uuid: "77", name: "Status Fault", format: .uint8, permissions: [.pairedRead, .events], minValue: 0, maxValue: 1, minStep: 1, validValues: [0, 1])
    public static let statusTampered = CharacteristicType(
        uuid: "7A", name: "Status Tampered", format: .uint8, permissions: [.pairedRead, .events], minValue: 0, maxValue: 1, minStep: 1, validValues: [0, 1])
    public static let statusLowBattery = CharacteristicType(
        uuid: "79", name: "Status Low Battery", format: .uint8, permissions: [.pairedRead, .events], minValue: 0, maxValue: 1, minStep: 1, validValues: [0, 1])
    public static let batteryLevel = CharacteristicType(
        uuid: "68", name: "Battery Level", format: .uint8, permissions: [.pairedRead, .events], unit: .percentage, minValue: 0, maxValue: 100, minStep: 1)
    public static let chargingState = CharacteristicType(
        uuid: "8F", name: "Charging State", format: .uint8, permissions: [.pairedRead, .events], minValue: 0, maxValue: 2, minStep: 1, validValues: [0, 1, 2])
}
