// Portions derived from HAP-NodeJS (https://github.com/homebridge/HAP-NodeJS), Apache License 2.0. Modified for CameraBridge.
// GENERATED by Tools/hap-definitions/generate.mjs from HAP-NodeJS lib/ServiceDefinitions.ts (research brief §3.4 subset).
// Do not edit by hand: change the generator's subset and rerun it.

import Foundation

extension ServiceType {
    /// Optional characteristics not in the subset: accessoryFlags, appMatchingIdentifier, matterFirmwareRevisionNumber, hardwareFinish, productData, softwareRevision.
    public static let accessoryInformation = ServiceType(
        uuid: "3E", name: "Accessory Information",
        required: [CharacteristicType.identify, .manufacturer, .model, .name, .serialNumber, .firmwareRevision],
        optional: [CharacteristicType.configuredName, .hardwareRevision])
    public static let protocolInformation = ServiceType(
        uuid: "A2", name: "Protocol Information",
        required: [CharacteristicType.version],
        optional: [])
    public static let cameraRTPStreamManagement = ServiceType(
        uuid: "110", name: "Camera RTP Stream Management",
        required: [CharacteristicType.selectedRTPStreamConfiguration, .setupEndpoints, .streamingStatus, .supportedAudioStreamConfiguration, .supportedRTPConfiguration, .supportedVideoStreamConfiguration],
        optional: [CharacteristicType.active])
    public static let cameraRecordingManagement = ServiceType(
        uuid: "204", name: "Camera Recording Management",
        required: [CharacteristicType.active],
        optional: [CharacteristicType.recordingAudioActive, .selectedCameraRecordingConfiguration, .supportedAudioRecordingConfiguration, .supportedCameraRecordingConfiguration, .supportedVideoRecordingConfiguration])
    public static let cameraOperatingMode = ServiceType(
        uuid: "21A", name: "Camera Operating Mode",
        required: [CharacteristicType.eventSnapshotsActive, .homeKitCameraActive],
        optional: [CharacteristicType.cameraOperatingModeIndicator, .manuallyDisabled, .nightVision, .periodicSnapshotsActive, .thirdPartyCameraActive, .diagonalFieldOfView])
    public static let dataStreamTransportManagement = ServiceType(
        uuid: "129", name: "Data Stream Transport Management",
        required: [CharacteristicType.setupDataStreamTransport, .supportedDataStreamTransportConfiguration, .version],
        optional: [])
    public static let microphone = ServiceType(
        uuid: "112", name: "Microphone",
        required: [CharacteristicType.mute],
        optional: [CharacteristicType.volume])
    public static let speaker = ServiceType(
        uuid: "113", name: "Speaker",
        required: [CharacteristicType.mute],
        optional: [CharacteristicType.active, .volume])
    /// Optional characteristics not in the subset: brightness, operatingStateResponse.
    public static let doorbell = ServiceType(
        uuid: "121", name: "Doorbell",
        required: [CharacteristicType.programmableSwitchEvent],
        optional: [CharacteristicType.mute, .name, .volume])
    /// Optional characteristics not in the subset: serviceLabelIndex.
    public static let statelessProgrammableSwitch = ServiceType(
        uuid: "89", name: "Stateless Programmable Switch",
        required: [CharacteristicType.programmableSwitchEvent],
        optional: [CharacteristicType.name])
    public static let motionSensor = ServiceType(
        uuid: "85", name: "Motion Sensor",
        required: [CharacteristicType.motionDetected],
        optional: [CharacteristicType.name, .statusActive, .statusFault, .statusLowBattery, .statusTampered])
    public static let occupancySensor = ServiceType(
        uuid: "86", name: "Occupancy Sensor",
        required: [CharacteristicType.occupancyDetected],
        optional: [CharacteristicType.name, .statusActive, .statusFault, .statusLowBattery, .statusTampered])
    public static let lightSensor = ServiceType(
        uuid: "84", name: "Light Sensor",
        required: [CharacteristicType.currentAmbientLightLevel],
        optional: [CharacteristicType.name, .statusActive, .statusFault, .statusLowBattery, .statusTampered])
    public static let temperatureSensor = ServiceType(
        uuid: "8A", name: "Temperature Sensor",
        required: [CharacteristicType.currentTemperature],
        optional: [CharacteristicType.name, .statusActive, .statusFault, .statusLowBattery, .statusTampered])
    public static let humiditySensor = ServiceType(
        uuid: "82", name: "Humidity Sensor",
        required: [CharacteristicType.currentRelativeHumidity],
        optional: [CharacteristicType.name, .statusActive, .statusFault, .statusLowBattery, .statusTampered])
    public static let contactSensor = ServiceType(
        uuid: "80", name: "Contact Sensor",
        required: [CharacteristicType.contactSensorState],
        optional: [CharacteristicType.name, .statusActive, .statusFault, .statusLowBattery, .statusTampered])
    public static let battery = ServiceType(
        uuid: "96", name: "Battery",
        required: [CharacteristicType.statusLowBattery],
        optional: [CharacteristicType.batteryLevel, .chargingState, .name])
    public static let `switch` = ServiceType(
        uuid: "49", name: "Switch",
        required: [CharacteristicType.on],
        optional: [CharacteristicType.name])
}
