import BridgeSupport
import Foundation
import Testing
@testable import HAPCore

// Goldens generated by HAP-NodeJS 2.2.3 (Interop/node/goldens.mjs, plan task W1-9): Fixtures/tlv8.json and
// Fixtures/setup-payload.json, read via #filePath (the target excludes Fixtures from its sources).

private func fixtureURL(_ name: String) -> URL {
    URL(fileURLWithPath: #filePath).deletingLastPathComponent().appending(path: "Fixtures/\(name)")
}

private func hexData(_ string: String) throws -> Data { try #require(Data(hex: string)) }

struct TLV8FixtureItem: Decodable, Sendable {
    var type: UInt8
    var value: String

    func item() throws -> TLV8.Item { TLV8.Item(type, try hexData(value)) }
}

struct TLV8EncodeCase: Decodable, Sendable, CustomTestStringConvertible {
    var name: String
    var items: [TLV8FixtureItem]
    var encoded: String
    var testDescription: String { name }
}

struct TLV8DecodeCase: Decodable, Sendable, CustomTestStringConvertible {
    var name: String
    var encoded: String
    var items: [TLV8FixtureItem]
    var testDescription: String { name }
}

struct TLV8InvalidCase: Decodable, Sendable, CustomTestStringConvertible {
    var name: String
    var encoded: String
    var error: String
    var type: UInt8?
    var testDescription: String { name }
}

struct TLV8ListCase: Decodable, Sendable, CustomTestStringConvertible {
    var name: String
    var encoded: String
    var separator: UInt8
    var groups: [[TLV8FixtureItem]]
    var testDescription: String { name }
}

private struct TLV8Fixture: Decodable {
    var encode: [TLV8EncodeCase]
    var decode: [TLV8DecodeCase]
    var invalid: [TLV8InvalidCase]
    var lists: [TLV8ListCase]

    static let shared: TLV8Fixture? = {
        guard let data = try? Data(contentsOf: fixtureURL("tlv8.json")) else { return nil }
        return try? JSONDecoder().decode(TLV8Fixture.self, from: data)
    }()
}

@Suite struct TLV8FixtureTests {
    @Test func fixtureIsPresent() throws {
        let fixture = try #require(TLV8Fixture.shared)
        #expect(fixture.encode.count >= 10)
        #expect(fixture.decode.count >= 10)
        #expect(fixture.invalid.count >= 4)
        #expect(fixture.lists.count >= 2)
    }

    @Test(arguments: TLV8Fixture.shared?.encode ?? [])
    func encodesLikeHAPNodeJS(_ testCase: TLV8EncodeCase) throws {
        let items = try testCase.items.map { try $0.item() }
        #expect(TLV8.encode(items).hexString == testCase.encoded)
        // TLVBuilder writes the same bytes.
        var builder = TLVBuilder()
        for item in items { builder.add(item.type, item.value) }
        #expect(builder.data.hexString == testCase.encoded)
    }

    @Test(arguments: TLV8Fixture.shared?.decode ?? [])
    func decodesLikeHAPNodeJS(_ testCase: TLV8DecodeCase) throws {
        let decoded = try TLV8.decode(try hexData(testCase.encoded))
        #expect(decoded == (try testCase.items.map { try $0.item() }))
        #expect(try TLVReader(try hexData(testCase.encoded)).items == decoded)
    }

    @Test(arguments: TLV8Fixture.shared?.invalid ?? [])
    func rejectsWhatHAPNodeJSRejects(_ testCase: TLV8InvalidCase) throws {
        let expected: TLV8Error
        switch testCase.error {
        case "truncated": expected = .truncated
        case "invalidLength": expected = .invalidLength(try #require(testCase.type))
        default:
            Issue.record("unknown error kind \(testCase.error)")
            return
        }
        let data = try hexData(testCase.encoded)
        #expect(throws: expected) { try TLV8.decode(data) }
    }

    @Test(arguments: TLV8Fixture.shared?.lists ?? [])
    func splitsListsLikeHAPNodeJS(_ testCase: TLV8ListCase) throws {
        let groups = TLV8.splitList(try TLV8.decode(try hexData(testCase.encoded)), separator: testCase.separator)
        #expect(groups == (try testCase.groups.map { try $0.map { try $0.item() } }))
    }
}

struct SetupURICase: Decodable, Sendable, CustomTestStringConvertible {
    var code: String
    var setupID: String
    var category: UInt16
    var uri: String
    var testDescription: String { "\(setupID) category \(category)" }
}

struct SetupHashCase: Decodable, Sendable, CustomTestStringConvertible {
    var setupID: String
    var deviceID: String
    var hash: String
    var testDescription: String { "\(setupID) \(deviceID)" }
}

private struct SetupPayloadFixture: Decodable {
    var uris: [SetupURICase]
    var setupHashes: [SetupHashCase]

    static let shared: SetupPayloadFixture? = {
        guard let data = try? Data(contentsOf: fixtureURL("setup-payload.json")) else { return nil }
        return try? JSONDecoder().decode(SetupPayloadFixture.self, from: data)
    }()
}

@Suite struct SetupPayloadFixtureTests {
    @Test func fixtureIsPresent() throws {
        let fixture = try #require(SetupPayloadFixture.shared)
        #expect(fixture.uris.count >= 25)
        #expect(fixture.setupHashes.count >= 12)
        // The brief §3.3 goldens are among them.
        #expect(fixture.uris.contains { $0.code == "031-45-154" && $0.setupID == "7OSX" && $0.category == 17 && $0.uri == "X-HM://00GW95DQA7OSX" })
        #expect(fixture.setupHashes.contains { $0.setupID == "7OSX" && $0.deviceID == "CC:22:3D:E3:CE:F3" && $0.hash == "7JWHTA==" })
    }

    @Test(arguments: SetupPayloadFixture.shared?.uris ?? [])
    func setupURIMatchesHAPNodeJS(_ testCase: SetupURICase) throws {
        let code = try #require(SetupCode(testCase.code))
        let category = try #require(AccessoryCategory(rawValue: testCase.category))
        #expect(SetupPayload.uri(code: code, setupID: testCase.setupID, category: category) == testCase.uri)
    }

    @Test(arguments: SetupPayloadFixture.shared?.setupHashes ?? [])
    func setupHashMatchesHAPNodeJS(_ testCase: SetupHashCase) throws {
        let deviceID = try #require(DeviceID(testCase.deviceID))
        #expect(SetupPayload.setupHash(setupID: testCase.setupID, deviceID: deviceID) == testCase.hash)
    }
}
