import BridgeSupport
import Foundation
import HAPCore
@testable import HAPCamera

/// `Fixtures/camera-tlv.json` (generated by `Interop/node/goldens.mjs camera` from HAP-NodeJS 2.2.3), read relative to
/// this file (no SwiftPM resources).
struct CameraTLVGoldens: Decodable {
    struct AudioCodecOption: Decodable {
        var codec: UInt8
        var sampleRates: [UInt8]
        var channels: Int
        var bitrateMode: Int
    }

    struct StreamingOptions: Decodable {
        var resolutions: [[Int]]
        var profiles: [UInt8]
        var levels: [UInt8]
        var audioCodecs: [AudioCodecOption]
        var comfortNoise: Bool
        var twoWayAudio: Bool
        var cryptoSuites: [UInt8]
    }

    struct StreamingCase: Decodable {
        var name: String
        var decodeOnly: Bool?
        var options: StreamingOptions
        var supportedVideoStreamConfiguration: String
        var supportedAudioStreamConfiguration: String
        var supportedRTPConfiguration: String
    }

    struct RecordingOptions: Decodable {
        var isDoorbell: Bool
        var prebufferLengthMs: Int
        var fragmentLengthMs: Int
        var resolutions: [[Int]]
        var profiles: [UInt8]
        var levels: [UInt8]
        var audioCodec: UInt8
        var audioSampleRates: [UInt8]
        var audioChannels: Int
        var audioBitrateMode: Int
        var eventTriggers: UInt64
    }

    struct RecordingCase: Decodable {
        var name: String
        var options: RecordingOptions
        var supportedCameraRecordingConfiguration: String
        var supportedVideoRecordingConfiguration: String
        var supportedAudioRecordingConfiguration: String
    }

    struct SelectedConfiguration: Decodable {
        struct Resolution: Decodable {
            var width: Int
            var height: Int
            var fps: Int
        }

        var prebufferLengthMs: Int
        var eventTriggers: UInt64
        var fragmentLengthMs: Int
        var videoProfile: UInt8
        var videoLevel: UInt8
        var videoBitrateKbps: Int
        var iFrameIntervalMs: Int
        var resolution: Resolution
        var audioCodec: UInt8
        var audioChannels: Int
        var audioSampleRate: UInt8
        var audioMaxBitrateKbps: Int
    }

    struct SelectedCase: Decodable {
        var name: String
        var encoded: String
        var configuration: SelectedConfiguration
    }

    struct DataStreamTransport: Decodable {
        var supportedDataStreamTransportConfiguration: String
    }

    struct StreamingStatus: Decodable {
        var available: String
        var inUse: String
        var unavailable: String
    }

    var streaming: [StreamingCase]
    var recording: [RecordingCase]
    var selectedRecordingConfiguration: [SelectedCase]
    var dataStreamTransport: DataStreamTransport
    var streamingStatus: StreamingStatus
    var setupEndpointsDefault: String

    static func load() throws -> CameraTLVGoldens {
        let url = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
            .appending(path: "Fixtures/camera-tlv.json")
        return try JSONDecoder().decode(CameraTLVGoldens.self, from: Data(contentsOf: url))
    }
}

struct FixtureError: Error, CustomStringConvertible {
    var description: String
}

extension CameraTLVGoldens.StreamingOptions {
    func cameraStreamingOptions() throws -> CameraStreamingOptions {
        CameraStreamingOptions(
            resolutions: try resolutions.map(videoResolution),
            profiles: try profiles.map { try require(H264Profile(rawValue: $0), "profile \($0)") },
            levels: try levels.map { try require(H264Level(rawValue: $0), "level \($0)") },
            audioCodecs: try audioCodecs.map { option in
                (codec: try require(StreamingAudioCodec(rawValue: option.codec), "codec \(option.codec)"),
                 sampleRates: try option.sampleRates.map { try require(StreamingSampleRate(rawValue: $0), "rate \($0)") })
            },
            twoWayAudio: twoWayAudio,
            cryptoSuites: try cryptoSuites.map { try require(SRTPCryptoSuite(rawValue: $0), "suite \($0)") })
    }
}

extension CameraTLVGoldens.RecordingOptions {
    func cameraRecordingOptions() throws -> CameraRecordingOptions {
        CameraRecordingOptions(
            prebufferLengthMs: prebufferLengthMs, fragmentLengthMs: fragmentLengthMs,
            resolutions: try resolutions.map(videoResolution),
            profiles: try profiles.map { try require(H264Profile(rawValue: $0), "profile \($0)") },
            levels: try levels.map { try require(H264Level(rawValue: $0), "level \($0)") },
            audioCodec: try require(RecordingAudioCodec(rawValue: audioCodec), "codec \(audioCodec)"),
            audioSampleRates: try audioSampleRates.map { try require(RecordingSampleRate(rawValue: $0), "rate \($0)") },
            audioChannels: audioChannels)
    }
}

extension CameraTLVGoldens.SelectedConfiguration {
    func cameraRecordingConfiguration() throws -> CameraRecordingConfiguration {
        CameraRecordingConfiguration(
            prebufferLengthMs: prebufferLengthMs, eventTriggers: eventTriggers, fragmentLengthMs: fragmentLengthMs,
            videoProfile: try require(H264Profile(rawValue: videoProfile), "profile"),
            videoLevel: try require(H264Level(rawValue: videoLevel), "level"),
            videoBitrateKbps: videoBitrateKbps, iFrameIntervalMs: iFrameIntervalMs,
            resolution: VideoResolution(resolution.width, resolution.height, resolution.fps),
            audioCodec: try require(RecordingAudioCodec(rawValue: audioCodec), "audio codec"),
            audioChannels: audioChannels,
            audioSampleRate: try require(RecordingSampleRate(rawValue: audioSampleRate), "audio rate"),
            audioMaxBitrateKbps: audioMaxBitrateKbps)
    }
}

private func videoResolution(_ triple: [Int]) throws -> VideoResolution {
    guard triple.count == 3 else { throw FixtureError(description: "resolution \(triple)") }
    return VideoResolution(triple[0], triple[1], triple[2])
}

private func require<T>(_ value: T?, _ what: String) throws -> T {
    guard let value else { throw FixtureError(description: "fixture value out of range: \(what)") }
    return value
}

func hex(_ string: String) throws -> Data {
    guard let data = Data(hex: string) else { throw FixtureError(description: "bad hex \(string)") }
    return data
}
