import Foundation
import MediaCore
import Testing
@testable import PlatformLinux

struct TestFailure: Error, CustomStringConvertible {
    let description: String
    init(_ description: String) { self.description = description }
}

/// Shared helpers: the real ffmpeg (tests that need it are skipped without one), a source stream generated by ffmpeg itself, and
/// bounded waits.
enum FFmpegTesting {
    static let executable: URL? = FFmpegCodecsConfiguration().resolveExecutable()
    static var available: Bool { executable != nil }

    static let capabilities: FFmpegCapabilities? = try? makeRuntime().capabilities()
    static var canEncodeHEVC: Bool { capabilities?.encoders.contains("libx265") ?? false }
    static var canEncodeOpus: Bool { capabilities?.hasOpus ?? false }
    /// drawtext and a font are available (the timestamp overlay can be drawn).
    static let canDrawOverlay: Bool = available && makeCodecs().runtime.overlayFont() != nil

    static func makeCodecs(_ configuration: FFmpegCodecsConfiguration = FFmpegCodecsConfiguration()) -> FFmpegMediaCodecs {
        FFmpegMediaCodecs(configuration: configuration)
    }

    static func makeRuntime(launcher: (any FFmpegProcessLaunching)? = nil, configuration: FFmpegCodecsConfiguration = FFmpegCodecsConfiguration()) -> FFmpegRuntime {
        FFmpegRuntime(launcher: launcher ?? SystemFFmpegLauncher(), configuration: configuration, executable: executable)
    }

    /// Compressed source pictures made by ffmpeg (testsrc2, libx264/libx265, no B-frames unless asked), 90 kHz PTS from 0 at `startPTS`.
    static func sourceFrames(codec: VideoCodec = .h264, width: Int = 320, height: Int = 180, fps: Int = 25, seconds: Double = 2, gop: Int = 25,
                             bFrames: Bool = false, startPTS: Int64 = 0) throws -> [EncodedVideoFrame] {
        let runtime = makeRuntime()
        var arguments = FFmpegArguments.common + ["-f", "lavfi", "-i", "testsrc2=size=\(width)x\(height):rate=\(fps)", "-t", "\(seconds)"]
        switch codec {
        case .h264:
            arguments += ["-c:v", "libx264", "-preset", "ultrafast", "-g", "\(gop)", "-bf", bFrames ? "2" : "0", "-sc_threshold", "0", "-pix_fmt", "yuv420p"]
        case .hevc:
            arguments += ["-c:v", "libx265", "-preset", "ultrafast", "-x265-params", "log-level=error:keyint=\(gop):min-keyint=\(gop):bframes=0", "-pix_fmt", "yuv420p"]
        }
        arguments += ["-f", "flv", "pipe:1"]
        let data = try FFmpegOneShot.run(runtime: runtime, label: "test source", arguments: arguments, input: nil, timeout: .seconds(30))
        var reader = FLVReader()
        var format: VideoFormat?
        var frames: [EncodedVideoFrame] = []
        for tag in reader.push(data) where tag.kind == .video {
            let payload = tag.payload
            if codec == .h264 {
                switch FLVAVCPacket.parse(tag) {
                case .sequenceHeader(let record)?:
                    let sets = try #require(FLVAVCPacket.parameterSets(avcC: record))
                    format = VideoFormat.h264(sps: sets.sps[0], pps: sets.pps[0])
                case .frame(let key, let composition, let nals)?:
                    let current = try #require(format)
                    frames.append(EncodedVideoFrame(format: current, nalUnits: nals.filter { ![6, 7, 8, 9].contains(NALUnits.h264Type($0)) }, isKeyframe: key,
                                                    pts: MediaTime(value: startPTS + (Int64(tag.timestamp) + Int64(composition)) * 90, timescale: 90_000),
                                                    dts: composition == 0 ? nil : MediaTime(value: startPTS + Int64(tag.timestamp) * 90, timescale: 90_000),
                                                    wallClock: Date(timeIntervalSinceReferenceDate: 800_000_000 + Double(tag.timestamp) / 1000)))
                default: break
                }
            } else {
                // Enhanced FLV: byte 0 = 0x80 | frame type << 4 | packet type, then the FourCC.
                guard payload.count > 5, payload[payload.startIndex] & 0x80 != 0 else { continue }
                let packetType = payload[payload.startIndex] & 0x0F
                let key = (payload[payload.startIndex] >> 4) & 0x07 == 1
                let body = payload.dropFirst(5)
                if packetType == 0 {
                    format = try hevcFormat(fromHvcC: Data(body))
                } else if packetType == 1 || packetType == 3 {
                    let current = try #require(format)
                    let composition = packetType == 1 ? Int64(Data(body).readInt24(at: 0)) : 0
                    let nals = NALUnits.splitLengthPrefixed(Data(body.dropFirst(packetType == 1 ? 3 : 0)))
                    frames.append(EncodedVideoFrame(format: current, nalUnits: nals.filter { ![32, 33, 34, 35, 39, 40].contains(NALUnits.hevcType($0)) }, isKeyframe: key,
                                                    pts: MediaTime(value: startPTS + (Int64(tag.timestamp) + composition) * 90, timescale: 90_000),
                                                    wallClock: Date(timeIntervalSinceReferenceDate: 800_000_000 + Double(tag.timestamp) / 1000)))
                }
            }
        }
        #expect(!frames.isEmpty, "the test source produced no frames")
        return frames
    }

    static func hevcFormat(fromHvcC record: Data) throws -> VideoFormat {
        let bytes = [UInt8](record)
        var index = 22
        let arrays = Int(bytes[index])
        index += 1
        var sets: [UInt8: Data] = [:]
        for _ in 0..<arrays {
            let type = bytes[index] & 0x3F
            let count = Int(bytes[index + 1]) << 8 | Int(bytes[index + 2])
            index += 3
            for _ in 0..<count {
                let length = Int(bytes[index]) << 8 | Int(bytes[index + 1])
                index += 2
                if sets[type] == nil { sets[type] = Data(bytes[index..<(index + length)]) }
                index += length
            }
        }
        guard let vps = sets[32], let sps = sets[33], let pps = sets[34], let format = VideoFormat.hevc(vps: vps, sps: sps, pps: pps) else {
            throw TestFailure("hvcC without usable parameter sets")
        }
        return format
    }

    /// Calls `body` until it returns a value, at most `timeout`.
    static func eventually<T>(timeout: Duration = .seconds(10), _ body: () async throws -> T?) async throws -> T? {
        let deadline = ContinuousClock.now + timeout
        while ContinuousClock.now < deadline {
            if let value = try await body() { return value }
            try await Task.sleep(for: .milliseconds(10))
        }
        return nil
    }
}
